apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    name: worker-pod
    author: intelliqit
spec:
  containers:
    - name: worker-pod
      image: dockersamples/examplevotingapp_worker
